name: flow_ai
description: AI-powered menstrual health tracking app that integrates with Flow-iQ
publish_to: 'none'
version: 2.0.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Firebase & Cloud Services - Updated for Swift 6 compatibility
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  
  # State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # HTTP & Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Charts & Data Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^24.2.9
  
  # UI Enhancements
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Date & Time
  intl: ^0.19.0
  table_calendar: ^3.0.9
  
  # Utilities
  uuid: ^4.2.1
  path_provider: ^2.1.1
  
  # Platform Integration
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Biometrics (for secure login)
  local_auth: ^2.1.7
  
  # Voice & Speech
  speech_to_text: ^6.6.0
  permission_handler: ^11.1.0
  
  # Health & Wearables
  health: ^10.2.0
  
  # Camera & Image Processing
  camera: ^0.10.5
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Machine Learning & AI - Using statistical models
  ml_algo: ^16.10.0
  ml_dataframe: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
