// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINPT4tmlaQtAWwUT3nAhwUXgvmuKFDO0',
    appId: '1:611364105058:web:dbdab29d0bcf7973321a3b',
    messagingSenderId: '611364105058',
    projectId: 'flow-iq-app',
    authDomain: 'flow-iq-app.firebaseapp.com',
    storageBucket: 'flow-iq-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChHW7mMC64--Y7d2mblgoNsPxHHInqFqg',
    appId: '1:611364105058:android:a57cfb3f97ceafad321a3b',
    messagingSenderId: '611364105058',
    projectId: 'flow-iq-app',
    storageBucket: 'flow-iq-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzpYBpar4tgsFc6ilcfjPBTefHg9kJuk',
    appId: '1:611364105058:ios:d86227ca33787cef321a3b',
    messagingSenderId: '611364105058',
    projectId: 'flow-iq-app',
    storageBucket: 'flow-iq-app.firebasestorage.app',
    iosBundleId: 'com.flowiq.flowIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzpYBpar4tgsFc6ilcfjPBTefHg9kJuk',
    appId: '1:611364105058:ios:d86227ca33787cef321a3b',
    messagingSenderId: '611364105058',
    projectId: 'flow-iq-app',
    storageBucket: 'flow-iq-app.firebasestorage.app',
    iosBundleId: 'com.flowiq.flowIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDINPT4tmlaQtAWwUT3nAhwUXgvmuKFDO0',
    appId: '1:611364105058:web:17ae9ed6eac8b966321a3b',
    messagingSenderId: '611364105058',
    projectId: 'flow-iq-app',
    authDomain: 'flow-iq-app.firebaseapp.com',
    storageBucket: 'flow-iq-app.firebasestorage.app',
  );

}